### ISSUE TITLE
how to register an `AsyncWorld` as a global variable in all `AsyncComputeTaskPool` contexts

### ISSUE THREAD

**Issue by databasedav** [dlom/bevy-async-ecs#2]
firstly, thanks so much for this library, i've recently started building a [signals](https://github.com/Pauan/rust-signals)-based bevy ui reactivity layer and this library is making it all much easier :pray: 

so basically i want to be able to access `AsyncWorld` from within any `AsyncComputeTaskPool` context to avoid having to either pass it through in more local scopes or only using it near systems with `&mut World`

i have this set up
```rust
static ASYNC_WORLD: OnceLock<AsyncWorld> = OnceLock::new();

fn async_world() -> &'static AsyncWorld {
    ASYNC_WORLD.get().expect("expected AsyncWorld to be initialized")
}

// system
fn init_async_world(world: &mut World) {
    ASYNC_WORLD.set(AsyncWorld::from_world(world));
    AsyncComputeTaskPool::get_or_init(|| {
        let task_pool = TaskPool::default();
        task_pool.with_local_executor(|_| {
            ASYNC_WORLD.set(AsyncWorld::from_world(world));
        });
        task_pool
    });
}
```

but when i try to access it with something like
```rust
async move {
    async_world().entity(entity).insert(BorderColor::from(c)).await;
}
```
running in a `AsyncComputeTaskPool::get().spawn(...)` i get the `.expect` from above

any idea how i can accomplish this? maybe a `thread_local!` somewhere? also i'm hoping this is a reasonable pattern, considering `AsyncWorld` is just a async channel wrapper

**Comment by dlom** [comment]
I've added an example here: https://github.com/dlom/bevy-async-ecs/blob/master/examples/global.rs

Additionally, I don't believe it's necessary to use `get_or_init` on the task pool.  Initializing the `OnceLock` in the system should be plenty.  The example reflects this.

**Comment by databasedav** [comment]
turns out i was panicking some of the time because my `init_async_world` was a `Startup` system along with another that used `async_world()`, thanks so much :pray:
